spring:
  cloud:
    stream:
      bindings:
        teamEvents-in-0:
          destination: clashBotTeamEvent
          content-type: application/json
          consumer:
            concurrency: 3
cloud:
  aws:
    stack:
      auto: false
aws:
  endpoint-configuration:
    url: http://host.docker.internal:4566
    signingRegion: us-east-1
logging:
  level:
    root: ERROR
    com.poss: INFO
