spring:
  application:
    name: clash-bot-event-consumer
management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  health:
    binders:
      enabled: true
clash-bot:
  event-stream:
    url: ${CLASH_BOT_STREAM_URL}
logging:
  level:
    root: ERROR
    com.poss: INFO
