name: Pull Request Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

jobs:
  build-artifact:
    name: Build Clash Bot Event Consumer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ClashBotEventConsumer

      - name: Checkout main OpenAPI Spec
        uses: actions/checkout@v3
        with:
          repository: Poss111/ClashBot-Service
          path: ClashBot-Service

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        working-directory: ClashBotEventConsumer
        run: |
          ls -lha
          CI=true ./gradlew clean build

      - uses: actions/upload-artifact@v3
        working-directory: ClashBotEventConsumer
        with:
          name: jar
          path: build/libs

  build-image:
    name: Build Docker image
    needs:
      - build-artifact
    runs-on: ubuntu-latest
    outputs:
      dockerTag: ${{ steps.meta.outputs.version }}
      fullDockerPath: ${{ steps.docker.outputs.fullDockerPath }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download built jar
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: build/libs

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            poss11111/clash-bot-event-consumer
          labels: |
            maintainer=Poss111
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JAR=${{ steps.docker.outputs.jar }}
